### PR TITLE
Support Vinyl files stream as replacement input

### PR DESCRIPTION
**Pull request by jraoult**
Sorry for the delay, it's been a very long time :( Hope you are still interested @VFK 

It is a WIP, I still have to write unit tests and update the README but I wanted to get your feedback before moving forward.

#### What's this PR do?
It allows to pass a stream of vinyl files as input of task `src` property everywhere a `string` value is accepted.

#### What are the relevant tickets?
https://github.com/VFK/gulp-html-replace/issues/25

### CODE REVIEW

**Comment by jraoult** [comment]
@VFK I noticed the build is failing in Node 10 because I used Promises to handle async task chain. Would you consider removing support for Node 10 or should I use an external dependency (bluebird may be)

**Comment by jraoult** [comment]
Reminder: tell users in the doc that the given content is assumed to be encoded in UTF8 and that if it is not they have to convert it before with something like https://www.npmjs.com/package/gulp-convert-encoding

**Comment by jraoult** [comment]
@VFK and chance to get your inputs on this PR?

**Comment by VFK** [comment]
@jraoult I'm really sorry for the delay, i was really busy these days.

Ok, so i checked your code and it's actually looks good. I was thinking about using something like `concat-stream` to wait for stream but Promises works too. 
As for removing v0.10 support - well, i do not collect any statistics on which nod version people use with this plugin. If just adding promises dependency is all it takes to support older node versions then i'd say let's do it. We can always break everything in v2.0 and make it "modern node only" thing :smile: I personally like bluebird and i suggest using it.

And sorry again for the delay, i'm always trying to answer faster but i can't always do that it seems.

**Comment by jraoult** [comment]
No problem @VFK, thanks for replying. I was myself supposed to do this PR almost 10 months ago so I can't really be too demanding here :D

Regarding your comments, I'll have a look over the week end and follow your recommendations.

**Comment by VFK** [comment]
Hey @jraoult testa are passing now, the code looks good. Can you please add tests for the new feature so i can merge and release?

**Comment by jraoult** [comment]
Hey @VFK, sorry for the delay. I was meant to do it two weeks ago already :/. I'll do my best to write the tests this week.

**Comment by jraoult** [comment]
Hey @VFK I finally took the time to finish this PR. Thanks for you patience here :) Could you have a final look at it?

Note that writing the test helped me to find a bug which I fixed, that is why this last commit is more than just unit tests.

**Comment by jraoult** [comment]
Hey @VFK have you had the time to take a look?

**Comment by VFK** [comment]
Hey @jraoult i'm sorry for the delay too 😄 
I took a look at the code and i like it. And also thank you for updating the readme, this is always nice. The code don't break the old tests and it adds the new ones so i'm going to merge it and bump the version. 
This really is what i wanted to add a long time ago but didn't have the time to do so so thank you again for your contribution!

**Comment by jraoult** [comment]
@VFK glad to help :)

**Pull request merged**
